version: '3'
# Other docker-compose examples in /examples

services:
    minecraft_new_map:
        container_name: omnos_minecraft
        image: itzg/minecraft-server
        ports:
           - "25565:25565"
        volumes:
           - ./data:/data
        environment:
            VERSION: 1.20.4
            TYPE: "SPIGOT"
            EULA: "TRUE"
            INIT_MEMORY: "8G"
            MAX_MEMORY: "8G"
            USE_AIKAR_FLAGS: "true"
        restart: always
